version: "3"
services:
  db:
    container_name: veritas-db
    image: postgres:latest
    profiles: [app, test]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veritas

  test-postgres-a:
    container_name: veritas-test-postgres-a
    image: postgres:latest
    profiles: [test]
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test-a
      POSTGRES_PASSWORD: password-a
      POSTGRES_DB: test-postgres-a
    volumes:
      - ./test/seed/a.sql:/docker-entrypoint-initdb.d/init.sql

  test-postgres-b:
    container_name: veritas-test-postgres-b
    image: postgres:latest
    profiles: [test]
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test-b
      POSTGRES_PASSWORD: password-b
      POSTGRES_DB: test-postgres-b
    volumes:
      - ./test/seed/b.sql:/docker-entrypoint-initdb.d/init.sql
